### ISSUE TITLE
Customized Responses

### ISSUE THREAD

**Issue by squijid** [Warped2713/mrprog#12]
hi i would like to be able to say "hey is everything going to be ok" and my robot boyfriend will say "yeah babe everything's gonna be ok, don't worry"

**Comment by 23nd** [comment]
The best way I can think to handle this is to pick a few scenarios (maybe 5?) and write custom phrase-response pairs for those scenarios.

For example:

Scenario: SeekSupport
Phrase: "** is|will ** be ok|okay **"
Response: happy/content/okay/withdrawn/upset: "yeah don't worry"

Squijid: @Cord.EXE will everything be ok?
Cord.EXE: yeah don't worry

Squijid: Is it going to be okay @Cord.EXE
Cord.EXE: yeah don't worry

Phrases can include wildcards and alternative spellings to make it easier for the code to recognize while giving you some natural language flexibility.


Do you have any other scenarios in mind?

**Comment by 23nd** [comment]
Early implementation has been added.

# Usage 
- `?>hey command_args_to_compare_with_custom_phrase`
- `@PartnerName command_args_to_compare_with_custom_phrase`
- If no command args are provided, partner will auto respond with "greeting" dialogue
- If the message contains only @PartnerName, the partner will auto respond with "fakenod" dialogue (pretending to understand what you said)
- Note: @PartnerName may appear anywhere in your message (and will be ignored if used inside of a custom phrase). All of the following will be considered equal:
    - Custom Phrase: Hello * world
    - Input: @PartnerName Hello blah world
    - Input: Hello blah world @PartnerName
    - Input: Hello @PartnerName blah world
    - Input: ?>hey Hello blah world
    - Input: ?>hey @PartnerName Hello blah world
    - Input: ?>hey Hello blah world @PartnerName
    - Input: ?>hey Hello blah @PartnerName world

# Custom Phrases
- Use a pipe ( | ) to mark a set of interchangeable words. EX: `hi|hello|hey`
- Spaces ( ) separate matchable units. EX: `hi|hello|hey there` will first check for the existence of one of `hi|hello|hey` in your first command argument before checking for the existence of  `there` in the second command argument
- Use an underscore ( _ ) to include optional contractions in a word set. EX: `do_not|don't` or `going_to|gonna`
- Use an asterisk ( * ) to specify a wildcard that matches any single word. EX: I am a * matches all of the following (and more!):
    - I am a hero
    - I am a pokemon
    - I am a potato
    - I am a !*#@
    - I am a 10

# Limitations
- Punctuation (!, ?, etc.) will be interpreted literally. If your phrase includes punctuation and your input does not (or vice-versa), it won't be a positive match
- You cannot use wildcards (*) in a word set (a|b|c), and underscores (_) used in word sets will be interpreted as empty space ( ). If a * is used in a word set, or a _ is used outside of a word set, they will be interpreted literally as * or _, respectively
- You are limited to 5 custom phrases
- Your custom phrases must have an official situation label (as listed in the downloadable custom dialogue/personality files). You cannot make up new situations, even if you add it to your custom file (they will be ignored).
- Your custom phrases must contain at least one character and cannot exceed 128 characters
- Custom phrases cannot consist of only wildcards (*)
- The matching function will return the first match found, so if you have multiple custom phrases that both match your input, only the first one will be used to fetch a response
- If something goes wrong in loading your file, you will receive a DM with a list of issues
